Rename _Atomic on which 'clang' choked.
Code had compiled sucessfully with

$ g++ --version
g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

However, with

$ clang --version
Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: i386-pc-linux-gnu
Thread model: posix

got the following

include/coe--local.h:72:1: error: declaration of anonymous class must be a definition
class _Atomic : private _Noncopyable {
^
include/coe--local.h:72:1: warning: declaration does not declare anything [-Wmissing-declarations]

Interestingly, word "_Atomic" was recognized by Vim and highlighted ;)

After rename to "_AtomIC", this 'clang' itself crashed :(

clang ...blah blah... src/coe-callback-sev.cpp
1.      <eof> parser at end of file
2.      include/coe-kernel--dcl.h:442:5: instantiating function definition 'HandlerX'
clang: error: unable to execute command: Segmentation fault (core dumped)